version: '3.8'

services:
  ecommerce:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce_web
    ports:
      - "8080:80"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__MyConnectionString=Server=sqlserver,1433;Database=EcommerceDB;User Id=sa;Password=Duong_vt147;TrustServerCertificate=True;
    restart: always

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ecommerce_sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Duong_vt147
      - MSSQL_PID=Express
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always

volumes:
  sqlserver_data: